### ISSUE TITLE
Πρόβλημα με το GitHub

### ISSUE THREAD

**Issue by mmits** [pibook/site#19]
Η σελίδα μου ενώ λειτουργούσε κανονικά χτες, σήμερα έκανα μια αλλαγή σ' ένα δικό μου αρχείο .md του /gr repository μου και τώρα μου δείχνει 404 error. Έχω ακούσει ότι κι άλλοι συμφοιτητές μου είχαν το ίδιο πρόβλημα. Επίσης, σήμερα το πρωί στο εργαστήριο, το GitHub είχε πέσει και δεν μπορούσε κανείς να συνδεθεί. Μήπως οφείλεται το πρόβλημά μου σ' αυτό;

**Comment by Helieus** [comment]
Και εγώ έχω το ίδιο πρόβλημα....

**Comment by lither-man** [comment]
Και εγώ έχω το ίδιο πρόβλημα στο μεταξύ εμένα με πετάει όταν μπαίνω στα repository μου..

**Comment by fotischris** [comment]
ΚΑΙ ΕΓΩ ΕΧΩ ΤΟ ΙΔΙΟ ΘΕΜΑ !!!!

**Comment by P17rant** [comment]
Μα καλά κύριε δώστε μια παράταση τώρα δεν είναι αυτά σοβαρά πράγματα...

**Comment by lither-man** [comment]
https://status.github.com/messages?fbclid=IwAR0xt95SJjnA8KURNxs3tjJ8c7UwNi2ecsFa8Yn0qf5BOx-hUoS_Nw1uXLQ


Δείτε αυτό παρακαλώ :)

**Comment by Helieus** [comment]
Ναι ισχύει όπως θέλει να εννοείσει ο συνάδελφος , το GitHub είναι νεκρό ... 

Source : https://status.github.com/messages
