### ISSUE TITLE
Επικοινωνία Ανθρώπου-Υπολογιστή απορία σχετικά με παραδοτέο 2 περιεχομένου

### ISSUE THREAD

**Issue by nikosbout** [pibook/site#33]
- [ ] Βρήκα ένα λάθος! Σας στέλνω με ένα λινκ την σελίδα του λάθους και δίνω περιγραφή για την διόρθωση
- [ ] Θέλω να προσθέσω νέο περιεχόμενο! Σας στέλνω με ένα λινκ το νέο περιεχόμενο σε ένα κλαδί στο δικό μου αντίγραφο του αποθετηρίου
- [x] 'Εχω μια απορία, την οποία σας γράφω παρακάτω
Πρέπει να δημιουργήσουμε νέα διαδραστικά παραδείγματα, ή πρέπει να πάρουμε ήδη υπάρχουσα διαδραστικά παραδείγματα απο κάποιον άλλο που τα έχει κοινοποιήσει και είναι διαθέσιμο για χρήση;
---

**Comment by epidrome** [comment]
θα τροποποιήσετε έτοιμα παραδείγματα που θα συμπληρώνουν αυτά που υπάρχουν

**Comment by nikosbout** [comment]
Τι είδους τροποποίηση πρέπει να κάνουμε; Και τα παραδείγματα πρέπει να τα βρούμε απ το διαδίκτυο πχ codepen;
