### ISSUE TITLE
Add Weiser Biography

### ISSUE THREAD

**Issue by VasNikos** [pibook/site#51]
- [ ] Βρήκα ένα λάθος! Σας στέλνω με ένα λινκ την σελίδα του λάθους και δίνω περιγραφή για την διόρθωση
- [x] Θέλω να προσθέσω νέο περιεχόμενο! Σας στέλνω με ένα λινκ το νέο περιεχόμενο σε ένα κλαδί στο δικό μου αντίγραφο του αποθετηρίου
- [ ] 'Εχω μια απορία, την οποία σας γράφω παρακάτω
---

https://github.com/VasNikos/gr/blob/gh-pages/_biography/bio-weiser.md
https://github.com/VasNikos/gr/blob/gh-pages/_biography/mark-weiser.md

https://vasnikos.github.io/gr/biography/mark-weiser/

**Comment by epidrome** [comment]
@VasNikos αν θέλετε να ανοίξετε ένα αίτημα για τα δύο νέα αρχεία ώστε να προστεθεί η συνεισφορά σας, ευχαριστώ!

**Comment by VasNikos** [comment]
Έχω σκοπό να τα προσθέσω αλλά έχω καθυστερήσει λόγω απειρίας. Στην προηγούμενη προσπάθεια κατάλαβα ότι δεν μπορώ να ανεβάσω μόνο τα συγκεκριμένα commits αλλά όλα τα commits μαζί με τις εικόνες. Σκέφτηκα να αποθηκεύσω τοπικά όλο το forked repository στον υπολογιστή μου, να το σβήσω και να το ξανακάνω fork για να προσθέσω μόνο τα δύο αρχεία. Υπάρχει πιο εύκολος τρόπος;

**Comment by epidrome** [comment]
σωστά, το γκτιχαμπ έχει αρκετούς περιορισμούς στην φαινομενικά εύχρηστη εκδοχή του στον ιστό, οπότε ο μόνος τρόπος με την διεπαφή της ιστοσελίδας είναι να γίνει τοπικό αντίγραφο μετά να σβηστεί το φορκ που έχετε, να γίνει νέο φορκ στο οποίο να προστεθεί μόνο το περιεχόμενο που μας ενδιαφέρει κατά προτίμηση σε νέο κλαδί (ώστε να αποφύγουμε πιθανές αλλαγές που θα έχουν γίνει στο μεσοδιάστημα σε άλλα αρχεία του κεντρικού από άλλους)

το ίδιο μπορεί να γίνει και με την διεπαφή σε γραμμή εντολών, χωρίς όμως τις διαγραφές, αλλά με κάποιες επιπλέον ρυθμίσεις

**Comment by VasNikos** [comment]
@epidrome καλησπέρα, έχω κάνει μια προσπάθεια για προσθήκη των αρχείων στο pull request `VasNikos add weiser-bio and authors update #52`.
