### ISSUE TITLE
image galery URLs

### ISSUE THREAD

**Issue by midipetit** [pibook/site#53]
@epidrome 
Κύριε Χωριανόπουλε καλημέρα,
έκανα την ανάρτηση για το βιβλίο με τις 2 εικόνες και το κείμενο. Το κείμενο και ο τίτλος εμφανίζονται στο Gallery αλλά όταν πατάω να το δω δεν εμφανίζεται η σελίδα και το url είναι το δικό σας και όχι το gh page που έχω δημιουργήσει εγω.
---

**Comment by epidrome** [comment]
υπάρχουν δύο λάθη:

1. στο αρχείο δήλωσης της εικόνας στον φάκελο _gallery το μονοπάτι προς την εικόνα δεν ανταποκρίνεται με την θέση της εικόνας στον φάκελο images
2. στον φάκελο images το αρχείο της μικρής εικόνας δεν έχει το σωστό δεύτερο μέρος

και για τα δύο λάθη απλά δες με προσοχή τα αντίστοιχα αρχεία για μερικές από τις 10αδες εικόνες που λειτουργούν κανονικά

**Comment by epidrome** [comment]
επίσης θα μπορούσες να αλλάξεις και τα μονοπάτια στις κεντρικές ρυθμίσεις της ιστοσελίδας
https://github.com/midipetit/gr/blob/gh-pages/_config.yml
αλλά αυτό δεν είναι απαραίτητο αφού όλες οι εικόνες, εκτός από τις νέες που πρόσθεσες φαίνονται κανονικά στο αντίγραφο σου
https://midipetit.github.io/gr/

**Comment by midipetit** [comment]
Αφού διόρθωσα τα λάθη στις εικόνες και πάλι δεν εμφανίζονταν, άλλαξα το path στο _config.yml και δούλεψε.

Ευχαριστώ.

**Comment by midipetit** [comment]
@epidrome 
ότι αλλαγή και αν κάνω στο βιβλίο μου έρχεται αυτό το mail και δεν μπορώ να το διορθώσω
The page build failed for the `gh-pages` branch with the following error:

A file was included in `_biography/alan-kay.md/#excerpt` that is a symlink or does not exist in your `_includes` directory. For more information, see https://help.github.com/en/articles/page-build-failed-file-is-a-symlink.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

**Comment by c18papa** [comment]
Καλησπέρα και Χρόνια Πολλά,

αντιμετωπίζω και εγώ ακριβώς το ίδιο πρόβλημα. ~~Το πρόβλημα φαίνεται να δημιουργείται από το παρακάτω include παρόλο που το αρχείο slides.html υπάρχει
`{% include slides.html caption="Εικόνες για την βιογραφία του Αλαν Κεη" %}`~~

**Comment by midipetit** [comment]
@c18papa Ιάσωνα, έβγαλες τελικά καμία άκρη;;

**Comment by c18papa** [comment]
@midipetit @epidrome 

Τελικά, αν καταλαβαίνω σωστά, μάλλον είναι κάποιο bug στη version 3.8.5 του Jekyll που χρησιμοποιεί το github-pages https://github.com/jekyll/jekyll/issues/7629, https://pages.github.com/versions/.

Δοκίμασα να αφαιρέσω τις γραμμές `{% include_relative bio-kay.md %}`, `{% include_relative bio-weiser.md %}` από τα αρχεία `alan-kay.md` και `mark-weiser.md` αντίστοιχα, όμως πάλι δεν γίνεται build καθώς το συγκεκριμένο include χρησιμοποιείται και σε άλλα αρχεία (π.χ στο `_case-study/affective.md`)

**Comment by epidrome** [comment]
@c18papa σωστά! λογικά τώρα θα δουλεύει αφού φαίνεται από την αντίστοιχη συζήτηση ότι το διόρθωσαν

@midipetit αν θέλετε να ανοίγετε νέα θέματα αφού η αρχική απορία ήταν για κάτι άλλο

**Comment by c18papa** [comment]
@epidrome δυστυχώς ακόμη δε δουλεύει

![image](https://user-images.githubusercontent.com/49448691/57192123-b1e47500-6f35-11e9-8ac7-a0a8f7bbd40d.png)

Να πειράξουμε τα αρχεία και να αφαιρέσουμε το include;

**Comment by epidrome** [comment]
@c18papa αν θέλετε να ανοίξετε ένα νέο θέμα στο δικό σας αποθετήριο να το δούμε εκεί
