### ISSUE TITLE
jekyll 3.8.5 in Github pages creates error with include files

### ISSUE THREAD

**Issue by epidrome** [pibook/site#55]
- [x] Βρήκα ένα λάθος! Σας στέλνω με ένα λινκ την σελίδα του λάθους και δίνω περιγραφή για την διόρθωση
- [ ] Θέλω να προσθέσω νέο περιεχόμενο! Σας στέλνω με ένα λινκ το νέο περιεχόμενο σε ένα κλαδί στο δικό μου αντίγραφο του αποθετηρίου
- [ ] 'Εχω μια απορία, την οποία σας γράφω παρακάτω
---

On github pages the error reports:
> Your site is having problems building: A file was included in _biography/alan-kay.md/#excerpt that is a symlink or does not exist in your _includes directory. For more information, see https://help.github.com/en/articles/page-build-failed-file-is-a-symlink. 

Locally the error is:
> jekyll 3.8.5 | Error:  Could not locate the included file 'bio-kay.md' in any of ["/home/choko/GitHub/mibookgr/_biography/alan-kay.md"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode.

**Comment by epidrome** [comment]
the site now builds locally with `jekyll v3.7.4`, as defined in the updated `Gemfile` 

this is a known and fixed jekyll bug https://github.com/jekyll/jekyll/pull/7633 but it has not yet made it to release https://github.com/jekyll/jekyll/releases

it should be available on Github Pages with v4+ sometime soon
https://pages.github.com/versions/

until then the site is frozen and can only be tested locally
https://jekyllrb.com/

**Comment by p12farm** [comment]
Έχω τρέξει το site τοπικά στον υπολογιστή μου. Υπάρχει τόπος να τρέξει στο Github Pages? Έχω δοκιμάσει ακόμα να να κάνω build to site τοπικά και να κάνω push το _site στο gh-pages, αλλά πάλι δεν τρέχει.

**Comment by epidrome** [comment]
αν τρέχει τοπικά, σίγουρα το στατικό αποτέλεσμα τρέχει και στο Github Pages αρκεί να γίνουν οι σωστές ρυμίσεις και να δωθούν οι κατάλληλες εντολές: 
https://stackoverflow.com/questions/28249255/how-do-i-configure-github-to-use-non-supported-jekyll-site-plugins/28252200#28252200

εναλλακτικά ίσως είναι πιο απλό το στατικό αποτέλεσμα (_site) να μπει σε νέο-διαφορετικό αποθετήριο από αυτό του πηγαίου κώδικα

**Comment by epidrome** [comment]
Update: Some six months after this bug was reported and fixed in `jekyll 3.8.6`, it has still not made it to Github Pages production, which is still locked in the buggy 3.8.5 https://pages.github.com/versions/

You can consistently replicate (the bug or the solution) locally by altering the jekyll versions in the Gemfile.

**Comment by vaggdim** [comment]
Για να το κάνω να τρέξει στο GitHub Pages άλλαξα το `include_relative` tag σε σκέτο `include` και μετέφερα τα αρχέια που είχαν αυτο το tag στο _includes directory.

**Comment by epidrome** [comment]
Update: Almost 9 months after the jekyll bug was reported and fixed, the deployed Github Pages gem is still the old one 😮 

Instead of waiting for the one year anniversary of this bug :trollface: i have configured the build at netlify, which is a good solution but not ideal since the site is fully supported by Github Pages.

**Comment by Sotiris132** [comment]
@epidrome Μπορώ μέσα στο ΣΚ να ζητήσω την βοήθεια σας με το error #55?

**Comment by epidrome** [comment]
at last 🙌 
GH pages now is with jekyll 3.8.7, so the bug is fixed
https://github.com/github/pages-gem/releases/tag/v205
