### ISSUE TITLE
Δεν μπορώ να φτιάξω το δικό μου mibook

### ISSUE THREAD

**Issue by Sotiris132** [pibook/site#64]
Στα settings όταν πάω να δω το url του mibook μου μου εμφανίζει αυτό

"Your site is having problems building: A file was included in pages/collections/making.md that is a symlink or does not exist in your _includes directory. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#file-is-a-symlink."

**Comment by epidrome** [comment]
#55
