### ISSUE TITLE
Αλλαγές στο Config

### ISSUE THREAD

**Issue by Helieus** [pibook/site#9]
- [X] 'Εχω μια απορία, την οποία σας γράφω παρακάτω
---
Καλησπέρα,

Τι αλλαγές χρειάζεται να κάνω στο config αρχείο του repository μου ;

**Comment by epidrome** [comment]
ίσως χρειάζεται να αλλάξουν κάποιες παράμετροι ώστε να αντιστοιχούν στο όνομα χρήστη και στο αποθετήριο σας, αλλά δεν ξέρω σίγουρα γιατί ποτέ δεν έχω κάνει φορκ το δικό μου αποθετήριο!
