### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by trospe** [pibook/site#96]
- [ x ] Βρήκα ένα λάθος! Σας στέλνω με ένα λινκ την σελίδα του λάθους και δίνω περιγραφή για την διόρθωση
- [ ] Θέλω να προσθέσω νέο περιεχόμενο! Σας στέλνω με ένα λινκ το νέο περιεχόμενο σε ένα κλαδί στο δικό μου αντίγραφο του αποθετηρίου
- [ ] 'Εχω μια απορία, την οποία σας γράφω παρακάτω
---
Καλησπέρα,το λάθος-πρόβλημα που αντιμετωπίζω είναι το εξής:
Όταν ενεργοποιώ το προσωπικό μου λινκ,στο δικό μου αποθετήριο,της σελίδας για να δω τις αλλαγές που έχω κάνει μου βγάζει αυτό το error το github.
( Your site is having problems building: The tag bibliography on line 5 in _chapter/archetypes.md is not a recognized Liquid tag. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.)
Το δοκίμασα και με καθαρό fork,χωρίς να αλλάξω τίποτα στον κώδικα και πάλι το ίδιο.
Δεν ξέρω αν έχω κανει εγώ κατι λάθος!
Ευχαριστώ! @epidrome

**Comment by epidrome** [comment]
@trospe 

ακούγεται σαν να προσπαθείς να το τρέξεις με γκιτχαμπ πεητζις, όμως αυτό δεν γίνεται, όπως λένε οι οδηγίες

οπότε μάλλον δεν ακολουθείς την οδηγία 2 για νετλιφαη

> 2. Go to Settings-->Github Pages and find your URL Configure the deployment from your netlify account.

για τέτοιου είδους προσωπικά προβλήματα παρακαλώ μην ανοίγετε εδώ θέματα αλλά στο δικό σας αποθετήριο, αφού το πρόβλημα είναι δικό σας και όχι εδώ!
