### ISSUE TITLE
Λάθος ανακατεύθυνση των συνδέσμων

### ISSUE THREAD

**Issue by vxsilis** [pibook/site#97]
- [ ] Θέλω να προσθέσω νέο περιεχόμενο! Σας στέλνω με ένα λινκ το νέο περιεχόμενο σε ένα κλαδί στο δικό μου αντίγραφο του αποθετηρίου
- [ ] Βρήκα ένα λάθος! Σας στέλνω με ένα λινκ την σελίδα του λάθους και δίνω περιγραφή για την διόρθωση
- [X] 'Εχω μια απορία, την οποία σας γράφω παρακάτω
---

Καλησπέρα,

Για το 5ο παραδοτέο του SW έκανα fork όλο το repo και τα _gallery και images, τα σύνδεσα με submodules σωστά (ελπίζω) αλλά όταν βρίσκομαι στην σελίδα βασισμένη στο δικό μου repo https://vxs5.netlify.app/gallery/ και πατάω την εικόνα που προόσθεσα με πηγαίνει στο url του original site, οπότε βγάζει error ότι το περιεχόμενο δεν υπάρχει. Πρέπει να αλλάξω κάποια άλλη ρύθμιση σε κάποια άλλο αρχείο για να με πηγαίνει στα δικά μου αρχεία και όχι του pibook? 

Για να γίνω και πιο συγκεκριμένος αν κατεβείτε κάτω και ψάξετε το "wordstar", που είναι η δικιά μου προσθήκη, θα καταλάβετε αυτήν την λάθος ανακατεύθυνση.

 Το repo μου είναι το https://github.com/vxsilis/site

Έχετε κάτι να προτείνετε? @epidrome

**Comment by epidrome** [comment]
update your `_config.yml`
